version: "3.8"

services:
  bp_pavuk_matus:
    build: .
    container_name: bp_pavuk_matus
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/bp_pavuk_matus
    privileged: true  # Povoliť špeciálne oprávnenia pre sieťovanie
    network_mode: "host"  # Na hostiteľskej sieti