version: "1.0"

services:
  networking_tool_service:
    build: .
    container_name: networking_tool
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/networking_tool
    privileged: true 
    network_mode: "host"